run-title: dqn-lunar-1
environment: LunarLander-v2
solved-criterion: 200
device: cuda:0
type: DDQN

train: false 
visualize: true


architecture:
  - 64
  - 64

max-experiences: 10_000
min-experiences: 128

batch-size: 128
lr-init: 5.e-4
lr-step: 25
lr-gamma: 0.9
weight-decay: 1.e-4

epsilon-start: 0.9
epsilon-min: 0.05
epsilon-decay: 0.99

tau: 0.999
gamma: 0.99
episodes: 50_000

save-path: models
load-path: ./models/ddqn-lunar-v2.pt
vis-episodes: 10